# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Salida', 'Salida'), ('Entrada', 'Entrada')], default='Salida', max_length=20)),
                ('day', models.DateField(help_text='D\xeda', verbose_name='D\xeda')),
                ('time', models.TimeField(help_text='Hora', verbose_name='Hora')),
                ('notes', models.TextField(blank=True, help_text='Observaciones', null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horario',
            },
        ),
    ]
