# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sonia', '0002_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='telefono',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
