# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sonia', '0003_auto_20190515_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='dni',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
